version: "3.8"

services:
  icecast:
    image: linuxserver/icecast
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}
    volumes:
      - ./icecast/icecast.xml:/config/icecast.xml:ro
    ports:
      - "${ICECAST_PORT:-8000}:8000"
    restart: unless-stopped

  liquidsoap:
    image: savonet/liquidsoap:2.2.5
    depends_on:
      - icecast
    environment:
      - TZ=${TZ}
      - LIQ_TELNET_PASSWORD=${LIQ_TELNET_PASSWORD}
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - STATION_MOUNT=${STATION_MOUNT}
      - STATION_NAME=${STATION_NAME}
    command: ["liquidsoap", "/radio.liq"]
    volumes:
      - ./liquidsoap/radio.liq:/radio.liq:ro
      - ./music:/music
    restart: unless-stopped

  queue-api:
    build: ./queue-api
    depends_on:
      - liquidsoap
    environment:
      - TZ=${TZ}
      - LIQ_HOST=liquidsoap
      - LIQ_PORT=1234
      - LIQ_PASS=${LIQ_TELNET_PASSWORD}
    ports:
      - "${QUEUE_PORT:-8080}:8080"
    restart: unless-stopped

# Optional named volume if you prefer (switch ./music bind above to music:)
# volumes:
#   music:
