services:
  icecast:
    image: libretime/icecast:2.4.4
    container_name: radio_icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD:-relaypass}
      - ICECAST_ADMIN_USER=${ICECAST_ADMIN_USER:-admin}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME:-0.0.0.0}
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml:ro
    ports:
      - "8000:8000"
    restart: unless-stopped

  liquidsoap:
  image: savonet/liquidsoap:v2.3.1
  container_name: radio_liquidsoap
  depends_on:
    - icecast
  environment:
    - STATION_MOUNT=${STATION_MOUNT:-/stream}
    - STATION_NAME=${STATION_NAME:-My Radio}
    - OUTPUT_BITRATE=${OUTPUT_BITRATE:-128}
    - ICECAST_HOST=icecast
    - ICECAST_PORT=8000
    - ICECAST_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    - LIQ_TELNET_PORT=1234
  command: ["liquidsoap","/config/radio.liq"]   # <-- point to file in the mounted folder
  volumes:
    - ./liquidsoap:/config:ro                   # <-- mount the folder that contains radio.liq
    - ./music:/music:ro
  restart: unless-stopped


  queue-api:
    build: ./queue-api
    container_name: radio_queue_api
    depends_on:
      - liquidsoap
    environment:
      - LIQ_HOST=liquidsoap
      - LIQ_PORT=1234
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
