services:
  icecast:
    image: lscr.io/linuxserver/icecast2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml:ro
    ports:
      - "${ICECAST_PORT:-8000}:8000"
    restart: unless-stopped

  liquidsoap:
    image: savonet/liquidsoap:v2.3.1
    depends_on:
      - icecast
    environment:
      - TZ=${TZ}
      - LIQ_TELNET_PASSWORD=${LIQ_TELNET_PASSWORD}
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - STATION_MOUNT=${STATION_MOUNT}
      - STATION_NAME=${STATION_NAME}
    command: ["liquidsoap", "/radio.liq"]
    volumes:
      - ./liquidsoap/radio.liq:/radio.liq:ro
      - ./music:/music
    restart: unless-stopped

  queue-api:
    build: ./queue-api
    depends_on:
      - liquidsoap
    environment:
      - TZ=${TZ}
      - LIQ_HOST=liquidsoap
      - LIQ_PORT=1234
      - LIQ_PASS=${LIQ_TELNET_PASSWORD}
    ports:
      - "${QUEUE_PORT:-8080}:8080"
    restart: unless-stopped
